# Generated by Django 4.2.4 on 2024-03-09 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_recipe_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('Cakes', 'cakes'), ('icecream', 'Ice Cream'), ('cookies', 'Cookies'), ('candies', 'Candies'), ('pies', 'Pies'), ('tarts', 'Tarts'), ('poudings', 'Poudings'), ('vegan', 'Vegan'), ('other', 'Other')], max_length=20),
        ),
    ]
