# Generated by Django 4.2.4 on 2024-05-03 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_recipe_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('Cakes', 'cakes'), ('Ice Cream', 'ice-cream'), ('Cookies', 'cookies'), ('Candies', 'candies'), ('Pies', 'pies'), ('Tarts', 'tarts'), ('Pouddings', 'pouddings'), ('Vegan', 'vegan'), ('Other', 'other')], max_length=20),
        ),
    ]
