# Generated by Django 4.2.4 on 2024-05-03 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_alter_recipe_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('Cakes', 'Cakes'), ('IceCreams', 'IceCreams'), ('Cookies', 'Cookies'), ('Candies', 'Candies'), ('Pies', 'Pies'), ('Tarts', 'Tarts'), ('Pouddings', 'Pouddings'), ('Vegan', 'Vegan'), ('Other', 'Other')], max_length=20),
        ),
    ]
