# Generated by Django 4.2.4 on 2024-06-15 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0018_alter_recipe_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='image',
            new_name='image_url',
        ),
    ]
