# Generated by Django 4.2.4 on 2023-08-26 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='default_profile2.png', null=True, upload_to='profile_images/'),
        ),
    ]
